{"name": "test_assert", "status": "failed", "statusDetails": {"message": "AssertionError: hello\nassert 10 == 1\n  +10\n  -1", "trace": "self = <test_Pages.test_app.Testcalculator object at 0x0417AD18>\n\n    def test_assert(self):\n>       assert 10==1,'hello'\nE       AssertionError: hello\nE       assert 10 == 1\nE         +10\nE         -1\n\ntest_app.py:32: AssertionError"}, "start": 1594281394255, "stop": 1594281394262, "uuid": "0fbd1ebc-e71a-46e9-9e99-908e3014d69b", "historyId": "ea028a832e2db5a669e1d0e2b603bc55", "testCaseId": "30c239b73637c823a8066a0e2a5f17dd", "fullName": "test_app.Testcalculator#test_assert", "labels": [{"name": "suite", "value": "test_app"}, {"name": "subSuite", "value": "Testcalculator"}, {"name": "host", "value": "DESKTOP-0J5JM67"}, {"name": "thread", "value": "7580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_app"}]}